CREATE DATABASE  IF NOT EXISTS `dbIdentityBroker` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `dbIdentityBroker`;

--
-- Table structure for table `UM_ACCESS_TOKEN`
--

DROP TABLE IF EXISTS `UM_ACCESS_TOKEN`;
CREATE TABLE `UM_ACCESS_TOKEN` (
  `UM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `UM_TOKEN` varchar(200) DEFAULT NULL,
  `UM_STATUS` varchar(45) DEFAULT NULL,
  `UM_TENANT` varchar(45) DEFAULT NULL,
  `UM_LASTUPDATEDATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `UM_DOMAIN` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`UM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=189 DEFAULT CHARSET=utf8;

--
-- Table structure for table `UM_AGENT_CONNECTIONS`
--

DROP TABLE IF EXISTS `UM_AGENT_CONNECTIONS`;
CREATE TABLE `UM_AGENT_CONNECTIONS` (
  `UM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `UM_ACCESS_TOKEN_ID` int(11) DEFAULT NULL,
  `UM_NODE` varchar(100) DEFAULT NULL,
  `UM_STATUS` varchar(1) DEFAULT NULL,
  `UM_LASTUPDATEDATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `UM_SERVER_NODE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`UM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=88 DEFAULT CHARSET=utf8;